### ISSUE TITLE
ListHelper::getHighestQualityAudioIndex

### ISSUE THREAD

**Issue by emillind** [emillind/NewPipe#10]
- [x] Add CodeCoverage input.
- [x] Identify all branches and give each one an ID.
- [x] Add calls to CodeCoverage.visitBranch(id, data) for each branch.
- [x] Create test method where a CodeCoverage object is initialized.
- [x] Write the tests.

**Comment by joakimboman** [comment]
Will change this one from DownloadRunnable::run to ListHelper::getHighestQualityAudioIndex
