### ISSUE TITLE
Utility::getFileType

### ISSUE THREAD

**Issue by emillind** [emillind/NewPipe#11]
- [x] Add CodeCoverage input.
- [x] Identify all branches and give each one an ID.
- [x] Add calls to CodeCoverage.visitBranch(id, data) for each branch.
- [x] Create test method where a CodeCoverage object is initialized.
- [x] Write the tests.

**Comment by joakimboman** [comment]
Instead of CheckTranslations::main, do: 
**Utility::getFileType@129-138@./app/src/main/java/us/shandian/giga/util/Utility.java**
